# Core Configuration
sonar.projectKey=Speckit-Etapa1
sonar.projectName=Speckit-Etapa1
sonar.host.url=http://localhost:9000

# Define your source directories separated by a comma
sonar.sources=backend, frontend

# Exclusions (Crucial so you don't scan downloaded library files)
sonar.exclusions=**/node_modules/**, **/.venv/**, **/dist/**, **/build/**, **/*.spec.ts

# Language Specific settings (Optional)
sonar.language=py,ts
sonar.sourceEncoding=UTF-8
